name: GitLab to GitHub Sync

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: fetch gitlab repo
        run: |
          git remote add gitlab https://SiFli-bot:${{ secrets.GITLAB_TOKEN  }}@${{  secrets.GITLAB_URL  }}/${{  secrets.GITLAB_REPO  }}.git
          git fetch gitlab
          git push origin gitlab/main:main
      
      - name: create dispatch merge
        uses: actions/github-script@v7
        with:
          script: |
            const workflowId = 'merge_prs.yml';
            const ref = 'main';

            // 发起请求触发目标工作流，无需传递 inputs 字段
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowId,
              ref: ref
            });